export interface IWpCategory {
	cat_ID: number,
	cat_name: string,
	category_count: number,
	category_description: string,
	category_nicename: string,
	category_parent: number,
	checked: boolean,
	count: number,
	description: string,
	filter: string,
	name: string,
	parent: number,
	slug: string,
	taxonomy: string,
	term_group: number,
	term_id: number,
	term_taxonomy_id: number,
}
